from typing import Dict, Optional, Any

def _uniform_cost_triplet(value: Optional[float]) -> Dict[str, Optional[float]]:
    return {
        "min": value,
        "avg": value,
        "max": value,
    }


def _range_cost_triplet(value_min: Optional[float], value_max: Optional[float]) -> Dict[str, Optional[float]]:
    if value_min is None or value_max is None:
        return {"min": None, "avg": None, "max": None}
    return {
        "min": value_min,
        "avg": 0.5 * (value_min + value_max),
        "max": value_max,
    }


def _pipe_row(
    *,
    capacity_kw: float,
    lifetime: float,
    main_unpaved_min: float,
    main_unpaved_max: float,
    main_paved_min: float,
    main_paved_max: float,
    main_material: float,
    house_unpaved: Optional[float],
    house_paved: Optional[float],
    house_material: Optional[float],
) -> Dict[str, Any]:
    row = {
        "capacity_kw": capacity_kw,
        "lifetime": lifetime,
    }

    for suffix, value in _range_cost_triplet(main_unpaved_min, main_unpaved_max).items():
        row[f"main_unpaved_{suffix}"] = value

    for suffix, value in _range_cost_triplet(main_paved_min, main_paved_max).items():
        row[f"main_paved_{suffix}"] = value

    for suffix, value in _uniform_cost_triplet(main_material).items():
        row[f"main_material_{suffix}"] = value

    for suffix, value in _uniform_cost_triplet(house_unpaved).items():
        row[f"house_unpaved_{suffix}"] = value

    for suffix, value in _uniform_cost_triplet(house_paved).items():
        row[f"house_paved_{suffix}"] = value

    for suffix, value in _uniform_cost_triplet(house_material).items():
        row[f"house_material_{suffix}"] = value

    return row


def _house_station_row(
    *,
    efficiency: float,
    lifetime: float,
    specific_investment_min: float,
    specific_investment_max: float,
    equipment_share: float,
    installation_share: float,
    investment_min: float,
    investment_max: float,
    annual_om: float,
) -> Dict[str, Any]:
    return {
        "efficiency": efficiency,
        "lifetime": lifetime,
        "specific_investment_min": specific_investment_min,
        "specific_investment_avg": 0.5 * (specific_investment_min + specific_investment_max),
        "specific_investment_max": specific_investment_max,
        "equipment_share": equipment_share,
        "installation_share": installation_share,
        "investment_min": investment_min,
        "investment_avg": 0.5 * (investment_min + investment_max),
        "investment_max": investment_max,
        "annual_om": annual_om,
    }


def _pump_station_row(
    *,
    threshold_kw: float,
    lifetime: float,
    specific_investment_min: float,
    specific_investment_max: float,
    equipment_share: float,
    installation_share: float,
) -> Dict[str, Any]:
    return {
        "threshold_kw": threshold_kw,
        "lifetime": lifetime,
        "specific_investment_min": specific_investment_min,
        "specific_investment_avg": 0.5 * (specific_investment_min + specific_investment_max),
        "specific_investment_max": specific_investment_max,
        "equipment_share": equipment_share,
        "installation_share": installation_share,
    }

PMR_70 = {
    25: {
        "capacity_kw": 102,
        "lifetime": 50,
        "main_unpaved_min": 60.0,
        "main_unpaved_max": 200.0,
        "main_unpaved_avg": 130.0,
        "main_paved_min": 150.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 825.0,
        "main_material": 44,
        "house_unpaved": 1200,
        "house_paved": 7200,
        "house_material": 528,
    },
    32: {
        "capacity_kw": 169,
        "lifetime": 50,
        "main_unpaved_min": 60.0,
        "main_unpaved_max": 200.0,
        "main_unpaved_avg": 130.0,
        "main_paved_min": 150.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 825.0,
        "main_material": 52,
        "house_unpaved": 1200,
        "house_paved": 7200,
        "house_material": 624,
    },
    40: {
        "capacity_kw": 262,
        "lifetime": 50,
        "main_unpaved_min": 60.0,
        "main_unpaved_max": 200.0,
        "main_unpaved_avg": 130.0,
        "main_paved_min": 150.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 825.0,
        "main_material": 67,
        "house_unpaved": 1200,
        "house_paved": 7200,
        "house_material": 804,
    },
    50: {
        "capacity_kw": 410,
        "lifetime": 50,
        "main_unpaved_min": 60.0,
        "main_unpaved_max": 200.0,
        "main_unpaved_avg": 130.0,
        "main_paved_min": 150.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 825.0,
        "main_material": 92,
        "house_unpaved": 1440,
        "house_paved": 9600,
        "house_material": 1104,
    },
    63: {
        "capacity_kw": 651,
        "lifetime": 50,
        "main_unpaved_min": 60.0,
        "main_unpaved_max": 200.0,
        "main_unpaved_avg": 130.0,
        "main_paved_min": 150.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 825.0,
        "main_material": 121,
        "house_unpaved": 1440,
        "house_paved": 9600,
        "house_material": 1452,
    },
    75: {
        "capacity_kw": 928,
        "lifetime": 50,
        "main_unpaved_min": 80.0,
        "main_unpaved_max": 250.0,
        "main_unpaved_avg": 165.0,
        "main_paved_min": 200.0,
        "main_paved_max": 2000.0,
        "main_paved_avg": 1100.0,
        "main_material": 136,
        "house_unpaved": 1440,
        "house_paved": 9600,
        "house_material": 1632,
    },
    90: {
        "capacity_kw": 1334,
        "lifetime": 50,
        "main_unpaved_min": 80.0,
        "main_unpaved_max": 250.0,
        "main_unpaved_avg": 165.0,
        "main_paved_min": 200.0,
        "main_paved_max": 2000.0,
        "main_paved_avg": 1100.0,
        "main_material": 174,
        "house_unpaved": None,
        "house_paved": None,
        "house_material": None,
    },
    110: {
        "capacity_kw": 1994,
        "lifetime": 50,
        "main_unpaved_min": 100.0,
        "main_unpaved_max": 300.0,
        "main_unpaved_avg": 200.0,
        "main_paved_min": 250.0,
        "main_paved_max": 2500.0,
        "main_paved_avg": 1375.0,
        "main_material": 208,
        "house_unpaved": None,
        "house_paved": None,
        "house_material": None,
    },
    125: {
        "capacity_kw": 2572,
        "lifetime": 50,
        "main_unpaved_min": 100.0,
        "main_unpaved_max": 300.0,
        "main_unpaved_avg": 200.0,
        "main_paved_min": 250.0,
        "main_paved_max": 2500.0,
        "main_paved_avg": 1375.0,
        "main_material": 283,
        "house_unpaved": None,
        "house_paved": None,
        "house_material": None,
    },
}

KMR_110 = {
    20: {
        "capacity_kw": 102,
        "lifetime": 30,
        "main_unpaved_min": 200.0,
        "main_unpaved_max": 600.0,
        "main_unpaved_avg": 400.0,
        "main_paved_min": 378.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 939.0,
        "main_material": 70,
        "house_unpaved": 1200,
        "house_paved": 7200,
        "house_material": 840,
    },
    25: {
        "capacity_kw": 169,
        "lifetime": 30,
        "main_unpaved_min": 315.0,
        "main_unpaved_max": 650.0,
        "main_unpaved_avg": 482.5,
        "main_paved_min": 378.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 939.0,
        "main_material": 90,
        "house_unpaved": 1200,
        "house_paved": 7200,
        "house_material": 1080,
    },
    32: {
        "capacity_kw": 262,
        "lifetime": 30,
        "main_unpaved_min": 400.0,
        "main_unpaved_max": 700.0,
        "main_unpaved_avg": 550.0,
        "main_paved_min": 480.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 990.0,
        "main_material": 100,
        "house_unpaved": 1200,
        "house_paved": 7200,
        "house_material": 1200,
    },
    40: {
        "capacity_kw": 410,
        "lifetime": 30,
        "main_unpaved_min": 417.0,
        "main_unpaved_max": 750.0,
        "main_unpaved_avg": 583.5,
        "main_paved_min": 500.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 1000.0,
        "main_material": 140,
        "house_unpaved": 1440,
        "house_paved": 9600,
        "house_material": 1680,
    },
    50: {
        "capacity_kw": 651,
        "lifetime": 30,
        "main_unpaved_min": 417.0,
        "main_unpaved_max": 800.0,
        "main_unpaved_avg": 608.5,
        "main_paved_min": 500.0,
        "main_paved_max": 1500.0,
        "main_paved_avg": 1000.0,
        "main_material": 200,
        "house_unpaved": 1440,
        "house_paved": 9600,
        "house_material": 2400,
    },
    65: {
        "capacity_kw": 928,
        "lifetime": 30,
        "main_unpaved_min": 518.0,
        "main_unpaved_max": 850.0,
        "main_unpaved_avg": 684.0,
        "main_paved_min": 623.0,
        "main_paved_max": 2000.0,
        "main_paved_avg": 1311.5,
        "main_material": 240,
        "house_unpaved": 1440,
        "house_paved": 9600,
        "house_material": 2880,
    },
    80: {
        "capacity_kw": 1334,
        "lifetime": 30,
        "main_unpaved_min": 518.0,
        "main_unpaved_max": 900.0,
        "main_unpaved_avg": 709.0,
        "main_paved_min": 623.0,
        "main_paved_max": 2000.0,
        "main_paved_avg": 1311.5,
        "main_material": 280,
        "house_unpaved": 1440,
        "house_paved": 9600,
        "house_material": 3360,
    },
    100: {
        "capacity_kw": 1994,
        "lifetime": 30,
        "main_unpaved_min": 697.0,
        "main_unpaved_max": 1050.0,
        "main_unpaved_avg": 873.5,
        "main_paved_min": 867.0,
        "main_paved_max": 2500.0,
        "main_paved_avg": 1683.5,
        "main_material": 390,
        "house_unpaved": None,
        "house_paved": None,
        "house_material": None,
    },
    125: {
        "capacity_kw": 2572,
        "lifetime": 30,
        "main_unpaved_min": 722.0,
        "main_unpaved_max": 1150.0,
        "main_unpaved_avg": 936.0,
        "main_paved_min": 867.0,
        "main_paved_max": 2500.0,
        "main_paved_avg": 1683.5,
        "main_material": 560,
        "house_unpaved": None,
        "house_paved": None,
        "house_material": None,
    },
}

HOUSE_STATIONS = {
    15: {
        "efficiency": 95,
        "lifetime": 25,
        "specific_investment_min": 438.0,
        "specific_investment_max": 730.0,
        "specific_investment_avg": 584.0,
        "equipment_share": 60,
        "installation_share": 40,
        "investment_min": 6570,
        "investment_max": 10950,
        "investment_avg": 8760.0,
        "annual_om": 50,
    },
    30: {
        "efficiency": 95,
        "lifetime": 25,
        "specific_investment_min": 213.0,
        "specific_investment_max": 355.0,
        "specific_investment_avg": 284.0,
        "equipment_share": 60,
        "installation_share": 40,
        "investment_min": 6390,
        "investment_max": 10650,
        "investment_avg": 8520.0,
        "annual_om": 50,
    },
    50: {
        "efficiency": 95,
        "lifetime": 25,
        "specific_investment_min": 178.5,
        "specific_investment_max": 297.5,
        "specific_investment_avg": 238.0,
        "equipment_share": 60,
        "installation_share": 40,
        "investment_min": 8925,
        "investment_max": 14875,
        "investment_avg": 11900.0,
        "annual_om": 100,
    },
    200: {
        "efficiency": 98,
        "lifetime": 25,
        "specific_investment_min": 87.0,
        "specific_investment_max": 145.0,
        "specific_investment_avg": 116.0,
        "equipment_share": 70,
        "installation_share": 30,
        "investment_min": 17400,
        "investment_max": 29000,
        "investment_avg": 23200.0,
        "annual_om": 150,
    },
    500: {
        "efficiency": 98,
        "lifetime": 25,
        "specific_investment_min": 62.25,
        "specific_investment_max": 103.75,
        "specific_investment_avg": 83.0,
        "equipment_share": 70,
        "installation_share": 30,
        "investment_min": 31125,
        "investment_max": 51875,
        "investment_avg": 41500.0,
        "annual_om": 300,
    },
    1000: {
        "efficiency": 98,
        "lifetime": 25,
        "specific_investment_min": 41.25,
        "specific_investment_max": 68.75,
        "specific_investment_avg": 55.0,
        "equipment_share": 70,
        "installation_share": 30,
        "investment_min": 41250,
        "investment_max": 68750,
        "investment_avg": 55000.0,
        "annual_om": 500,
    },
}

PUMP_STATIONS = {
    "le_1000": {
        "threshold_kw": 1000,
        "lifetime": 40,
        "specific_investment_min": 184.0,
        "specific_investment_max": 276.0,
        "specific_investment_avg": 230.0,
        "equipment_share": 25,
        "installation_share": 75,
    },
    "gt_1000": {
        "threshold_kw": float("inf"),
        "lifetime": 40,
        "specific_investment_min": 69.0,
        "specific_investment_max": 104.0,
        "specific_investment_avg": 86.5,
        "equipment_share": 25,
        "installation_share": 75,
    },
}